apiVersion: v1
kind: Service
metadata:
  name: node-web-app-service
spec:
  selector:
    app: node-webapp   # FIXED → Must match your Deployment's label
  ports:
    - protocol: TCP
      port: 80         # Exposes port 80 to users (browser)
      targetPort: 3000 # Points to your Node.js container port
  type: LoadBalancer